export const FETCH_API_ALL_TASK = "FETCH_API_ALL_TASK";
export const FETCH_API_ALL_TASK_SUCCESS = "FETCH_API_ALL_TASK_SUCCESS";
export const FETCH_API_ALL_TASK_ERR = "FETCH_API_ALL_TASK_ERR";

export const FETCH_API = "FETCH_API";
export const FETCH_API_TASK_SUCCESS = "FETCH_API_TASK_SUCCESS";
export const FETCH_API_TASK_ERR = "FETCH_API_TASK_ERR";

export const ADD_TASK_API = "ADD_TASK_API";
export const ADD_TASK_API_SUCCESS = "ADD_TASK_API_SUCCESS";
export const ADD_TASK_API_ERR = "ADD_TASK_API_ERR";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_ERR = "DELETE_TASK_ERR";

export const UPDATE_STATUS = "UPDATE_STATUS ";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS ";
export const UPDATE_STATUS_ERR = "UPDATE_STATUS_ERR ";

export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_ERR = "UPDATE_TASK_ERR";
